# Wallpaper setup!
# To reload when you update config: Run `killall hyprpaper` and then `hyperpaper & disown`

# run `hyprctl monitors all` to see all your monitors!!! In order to create your setup.

preload = /home/logan/Downloads/fruti-green.jpg

wallpaper = eDP-1,/home/logan/Downloads/fruti-green.jpg
#wallpaper = HDMI-A-2,/home/logan/Downloads/fruti-green.jpg #regular TV in the family room
